version: "3"

services:
  web:
    build: .
    command: npm run serve
    ports:
      - ${PORT}:8080
    volumes:
      - /usr/app/web/node_modules
      - ./src:/usr/app/web/src
    environment:
      - VUE_APP_API_HOST=${VUE_APP_API_HOST}